### ISSUE TITLE
problem with angular cli 1.0.0-beta.24 and angular ^2.3.1 and aot

### ISSUE THREAD

**Issue by abadakhshan** [scttcper/toastr-ng2#44] opened 2016-12-22 07:16 UTC
hi
when i use "ng build --prod --aot "  i get this error:
"ERROR in Error encountered resolving symbol values statically. Could not resolve type GlobalToastConfig (position 96:23 in the original .ts file), resolving symbol ToastrConfig in G:/Work/ExamBot/ExamBot/ExamBot/node_modules/toastr-ng2/toastr-config.d.ts"

this happens only with --aot.

i use "toastr-ng2": "3.2.4"
tanx

**Comment by ghidoz** [comment] 2016-12-22 14:02
The same for me

**Comment by yarrgh** [comment] 2016-12-22 14:41
Confirmed. This doesn't happen in the demo application as it references the library directly without using npm. 

I'll start investigating soon assuming that it hasn't been fixed by the time I get back to this.

**Comment by yarrgh** [comment] 2016-12-22 15:59
Seems to be some issue when dealing with angular >= 2.4.0. If you use angular 2.3.1, it'll compile just fine. If you want an immediate fix, change your angular dependencies to be "~2.3.1" instead of "^2.3.1"

I'm still not sure where this bug lies (toastr-ng2, angular-cli, angular, etc.)

**Comment by scttcper** [comment] 2016-12-22 17:10
I'm able to recreate it with ./stage-release.sh. It's also not working...

**Comment by scttcper** [comment] 2016-12-22 19:38
Released 3.2.5

**Closed by scttcper** 2016-12-22 19:38 UTC
Labels: need: investigation, type: bug

**Comment by tstavinoha** [comment] 2017-02-16 19:10
This is still happening to me, when i use the approach: ToastrModule.forRoot({...}).
Not even building using aot, just plain ng serve.
configuring the lib using injection into AppComponent passes without errors.

cli - 1.0.0-beta.30
angular - 2.4.7

**Comment by scttcper** [comment] 2017-02-16 19:27
@tstavinoha just tried with @angular/cli 31 and ngx-toastr latest and it didn't throw anything.

**Comment by yarrgh** [comment] 2017-02-16 22:30
Not able to duplicate this either. What version of ngx-toastr are you using?

```@angular/cli - 1.0.0-beta.31
angular - 2.4.7
ngx-toastr - 4.2.1```
