### ISSUE TITLE
Incorrect timeOut after hover

### ISSUE THREAD

**Issue by yarrgh** [scttcper/toastr-ng2#13] opened 2016-09-16 14:46 UTC
The initial `timeOut` works perfectly until you hover over the toast and the `extendedTimeOut` takes affect. All subsequent toasts use the `extendedTimeOut` instead of the initial `timeOut`. This causes the toasts to disappear too quickly. 

I have left the config with the defaults. The `timeOut` was left at 5 seconds and the `extendedTimeOut` at 1 second. Initially all toasts are displayed for 5 seconds like they should be. Once I hover over the toast (and then away), the `extendedTimeOut` takes affect and all subsequent toasts disappear after 1 second instead of 5.

**Comment by scttcper** [comment] 2016-09-16 15:50
Confirmed. Doesn't work in the demo because it passes a new config every time.

**Comment by scttcper** [comment] 2016-09-16 16:10
fixed in 1.3.2, thanks.

**Closed by scttcper** 2016-09-16 16:10 UTC
Labels: bug
